CREATE DATABASE PRJ_AIFUD;

USE PRJ_AIFUD;

CREATE TABLE CLIENTE ( 
CLI_ID INT NOT NULL PRIMARY KEY IDENTITY,
CLI_NOME VARCHAR (70),
CLI_CPF CHAR (11) UNIQUE,
CLI_DataNascimento DATE NULL,
CLI_ENDERECO VARCHAR (100),
CLI_TELEFONE VARCHAR (20)
);

--select * from cliente;

--drop table FUNCIONÁRIO;

CREATE TABLE FUNCIONARIO (
FUNC_ID INT NOT NULL PRIMARY KEY IDENTITY,
FUNC_NOME VARCHAR (100),
FUNC_CPF CHAR(11),
FUNC_DataNascimento DATE NULL,
FUNC_ENDERECO VARCHAR (100),
FUNC_TELEFONE VARCHAR (20),
FUNC_TURNO VARCHAR (50),
FUNC_FUNCAO VARCHAR (100),
);

--select* from FORNECEDOR;

CREATE TABLE PRODUTO (
    PROD_ID INT NOT NULL PRIMARY KEY IDENTITY,
    PROD_RESTAURANTE INT,
    FOREIGN KEY (PROD_RESTAURANTE) REFERENCES RESTAURANTE(RES_ID) ON DELETE SET NULL,
    PROD_NOME VARCHAR(100),
    PROD_DESCRICAO VARCHAR(200),
    PROD_PRECO DECIMAL(9, 2),
    PROD_ESTOQUE DECIMAL(9, 1),
    PROD_UNIDMED VARCHAR(20)
);

--Drop table produto
--SELECT * FROM PRODUTO
CREATE TABLE FORNECEDOR(
	FOR_ID INT IDENTITY,
	FOR_CNPJ VARCHAR(14),
	FOR_NOME VARCHAR(200),
	FOR_RAMO VARCHAR(30),
	FOR_TELEFONE VARCHAR(20),
	FOR_ENDERECO VARCHAR(100)
);

CREATE TABLE RESTAURANTE(
	RES_ID INT IDENTITY PRIMARY KEY,
	RES_CNPJ VARCHAR(50),
	RES_NOME VARCHAR(50),
	RES_TEMA VARCHAR(30),
	RES_TELEFONE VARCHAR(20),
	RES_ENDERECO VARCHAR(100)
);

CREATE TABLE PEDIDO (
	PED_Id INT IDENTITY PRIMARY KEY,
	PED_DataHora DATETIME NOT NULL,
	CLI_ID INT NOT NULL,
	status CHAR(1) NOT NULL DEFAULT 'P',
	FOREIGN KEY (CLI_ID) REFERENCES CLIENTE (CLI_ID)
);

CREATE TABLE pedido_item (
	id_pedido_item INT IDENTITY,
	PED_ID INT NOT NULL,
	PROD_ID INT NOT NULL,
	QTD INT NOT NULL,
	VALOR_UN DECIMAL(18,2) NOT NULL DEFAULT '(0.00)',
	VALOR_TOTAL DECIMAL(18,2) NOT NULL DEFAULT '(0.00)',
	PRIMARY KEY (PED_ID, id_pedido_item),
	FOREIGN KEY (PED_ID) REFERENCES pedido (PED_ID),
	FOREIGN KEY (PROD_ID) REFERENCES produto (PROD_ID)
);



-- TABELA CARDÁPIO VAI PRECISAR DE UM FOREGN KEY COM A TABELA PRODUTO
CREATE TABLE CARDÁPIO(
	PROD_ID INT,
	FOREIGN KEY (PROD_ID) REFERENCES PRODUTO (PROD_ID),
	CAR_DESC VARCHAR (255),
	CAR_VALOR DECIMAL (9,2),
	TIPO_ITEM CHAR DEFAULT 'N'
);

select * from FUNCIONARIO;