CREATE DATABASE PRJ_AIFUD;

USE PRJ_AIFUD;

CREATE TABLE CLIENTE ( 
CLI_ID INT NOT NULL PRIMARY KEY IDENTITY,
CLI_NOME VARCHAR (70),
CLI_CPF CHAR (11) UNIQUE,
CLI_DataNascimento DATE NULL,
CLI_ENDERECO VARCHAR (100),
CLI_TELEFONE VARCHAR (20)
);

select * from cliente;

CREATE TABLE FUNCIONÁRIO (
FUNC_ID INT NOT NULL PRIMARY KEY IDENTITY,
FUNC_NOME VARCHAR (100),
FUNC_CPF CHAR(11),
UNC_TURNO VARCHAR (50),
FUNC_FUNCAO VARCHAR (100),
);

CREATE TABLE PRODUTO (
	PROD_ID INT NOT NULL PRIMARY KEY IDENTITY,
	PROD_NOME VARCHAR (100),
	PROD_DESCRICAO VARCHAR (200),
	PROD_PRECO DECIMAL (9, 2),
	PROD_QUANTIDADE DECIMAL (9, 1),
	PRO_UNIDMED VARCHAR (20),
);


-- TABELA PEDIDO VAI PRECISAR DE UM FOREGN KEY COM A TABELA PRODUTO
CREATE TABLE PEDIDO (
	PED_ID INT NOT NULL PRIMARY KEY IDENTITY,
	DATA_HORA DATETIME NOT NULL,
	CLI_ID INT NOT NULL,
	status CHAR(1) NOT NULL DEFAULT 'P',
	FOREIGN KEY (CLI_ID) REFERENCES cliente (CLI_ID)
);

CREATE TABLE PEDIDO_ITEM(
	ID_PED_ITEM INT IDENTITY,
	PED_ID INT,
	PROD_ID INT,
	QTD_ITEM INT,
	VLR_UNITARIO DECIMAL (7,2),
	VLR_TOTAL DECIMAL (9,2),
	PRIMARY KEY (PED_ID, ID_PED_ITEM),
	FOREIGN KEY (PED_ID) REFERENCES PEDIDO (PED_ID),
	FOREIGN KEY (PROD_ID) REFERENCES PRODUTO (PROD_ID),
);




-- TABELA CARDÁPIO VAI PRECISAR DE UM FOREGN KEY COM A TABELA PRODUTO
CREATE TABLE CARDÁPIO(
	PROD_ID INT,
	FOREIGN KEY (PROD_ID) REFERENCES PRODUTO (PROD_ID),
	CAR_DESC VARCHAR (255),
	CAR_VALOR DECIMAL (9,2),
	TIPO_ITEM CHAR DEFAULT 'N'
);